### ISSUE TITLE
Set emojis as reactions

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sinisimattia** [comment]
Per testare la traduzione automatica di Chrome? Stavo pensando di sostituirle con icone

**Comment by Nootso** [comment]
Sì è decisamente meglio

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
