### ISSUE TITLE
Ridurre il numero di articoli visualizzato in prima pagina a 10/15 altrimenti la gente non arriva a leggere in fondo le pagine "Redazione", ecc.

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#102]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sinisimattia** [comment]
Dopo la chiamata con Ale ci siamo accorti che questo va contro la SEO

**Comment by Nootso** [comment]
Cioè per la SEO è meglio averne tanti in home o pochi?

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
