### ISSUE TITLE
Redesign fixes ✨

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#146]
- Cambiare l'icona della faccia di Bill da mobile con Bill + megafono (non c'è bisogno di chiederla a Federica, ce l'ho io)
- Chiedere a Federica di aggiungere al logo di Sii come Bill Magazine Unconventional lo stickman con il megafono (non penso che questo influisca sulla pesantezza del file)
- Sostituire anche da desktop come da mobile il testo in alto a sinistra con il faccione di Bill (cliccabile che rimanda alla home)
- Dare più spazio alle immagini nelle anteprime degli articoli in home (ora si vedono in verticale, sarebbe meglio farle vedere più quadrate anche se questo toglie spazio a titolo e sottotitolo)
- Togliere lo sfondo blu agli sponsor e rimpicciolirli leggermente altrimenti sono più in evidenza degli articoli stessi
- Spostare in alto le sezioni degli articoli nelle anteprime della home
- Nel footer sostituire INSTAGRAM FACEBOOK GITHUB con loghi se non appesantiscono troppo

Poi ci sarebbe il discorso del poco testo nella home che avevamo affrontato con Ale, ma magari possiamo risolverlo più in là.
La cosa brutta a livello di immagine è che se cerchi Sii come Bill Magazine su Google appare come snippet il testo dello Sponsor del libro di Bill. Dovremmo avere una brevissima descrizione di quello che è il Magazine (in caso apro Issue a parte).

**Comment by sinisimattia** [comment]
@Nootso 

La prima sarebbe meglio non farla. Ho scelto quell'icona apposta perché quella con il megafono prende troppo spazio. L'icona dovrebbe essere il più semplice possibile.

Per quanto riguarda lo sfondo blu... sicuro? A me piace un casino. Almeno negli articoli lo posso lasciare in maniera che si distingua bene oppure lo metto più sul grigio chiaro? (che è meno evidente)

**Comment by sinisimattia** [comment]
@Nootso ho fatto delle prove con le immagini negli articoli. Se le lascio più libere prendono troppo spazio. Il titolo e gli altri testi dell'articolo andrebbero a capo molte più volte, risultando in articoli più lunghi e stretti. Posso ridurre il numero di colonne ad 1 su dispositivi tipo portatili e tablet, lasciandolo a 2 solo su dispositivi "xl" come desktop.

**Comment by Nootso** [comment]
Domanda stupida: se mettessimo in home gli articoli come sono in basso quando ne vengono suggeriti altri? Quindi foto quadrata e sopra la foto o sotto il titolo con nome autore. Così in una riga nella home riusciamo a metterne anche 3 o 4. Allego screen

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>

**Comment by sinisimattia** [comment]
@Nootso scusa ma se rispondi dalla mail non si vedono gli allegati

**Comment by sinisimattia** [comment]
@Nootso in ogni caso non funzionerebbe, il motivo per il quale sono in quel modo è perché tra gli articoli consigliati mettiamo meno info, quindi c'è meno testo e quindi non va a capo causando lo l'allargamento verticale delle immagini. Il componente (il blocco con immagine e testo di lato) è lo stesso utilizzato per entrambi.


P.S.
Io ti consiglio di ignorare questa cosa al momento, è talmente minuscola e fidati migliora il layout, ci consente di avere più articoli insieme sulla stessa riga e di utilizzare meno spazio.

**Comment by Nootso** [comment]
Un'altra cosa che ho notato è che anche da desktop sulla barra di navigazione c'è ESPLORA. Meglio lasciarla com'era prima almeno da desktop altrimenti costringiamo la gente a fare uno step in più.

**Comment by sinisimattia** [comment]
Ok
