### ISSUE TITLE
Eliminare le reaction

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#71]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sinisimattia** [comment]
@Nootso ci stavo pensando, non ci conviene. Con le reaction interne possiamo fare cose del tipo "Articoli di tendenza" etc... 
Per ora gli modifico lo stile poi dimmi te

**Comment by Nootso** [comment]
In che senso modifichi lo stile? Posso vedere un’anteprima?

Inviato da iPhone

**Comment by sinisimattia** [comment]
Appena pubblico si, in pratica le ho spostate a fine articolo. Mi sono reso conto che chiedere alle gente di lasciare mi piace prima di leggerlo non aveva senso
