### ISSUE TITLE
Aggiungere Disqus

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sinisimattia** [comment]
Disqus aggiunto, @Nootso vedi se ti piace sul sito demo.

**Comment by Nootso** [comment]
Sai che non lo vedo? Ho provato ad aprire tutti gli ultimi articoli della demo, vedo le reaction in fondo ma non Disqus

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
