### ISSUE TITLE
Scrivere sopra il primo articolo in cima alla home page "Articoli più recenti:"

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sinisimattia** [comment]
@Nootso siamo sicuri che serve?

**Comment by Nootso** [comment]
Secondo me sì, perché non caricandosi tutti la gente potrebbe pensare che siano tutti gli articoli pubblicati fino ad ora. È complicato?

Inviato da iPhone

**Comment by sinisimattia** [comment]
Non e' complicato, sarebbe un lavoro da due secondi. Magari sarebbe meglio trovare un'altra soluzione. Magari impaginando gli articoli

**Comment by Nootso** [comment]
Cosa intendi per impaginare?

**Comment by sinisimattia** [comment]
Come succede nella dashboard

**Comment by sinisimattia** [comment]
Decisione finale: impaginare articoli in home come succede nella dashboard.
Confermi @Nootso

**Comment by Nootso** [comment]
Yes!

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
