### ISSUE TITLE
Cambiare gli URL

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#77]
Sostituire i numeri degli URL con /categoria/parole-chiave come indicato nel documento scritti da Alessandro su Drive

**Comment by sinisimattia** [comment]
Puoi vedere le modifiche nel sito demo, fammi sapere che ne pensi

**Comment by Nootso** [comment]
Quali modifiche? Sto dando un’occhiata ora ma non trovo differenze, provo a cancellare la cache

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>

**Comment by Nootso** [comment]
Ah ok scusa, visto ora! Funziona, l’unica cosa è che se modifico gli URL vecchi scompaiono gli articoli ma non credo ci sia nulla da fare!

Grazie

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
