### ISSUE TITLE
Rimpicciolire i banner nella home

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#79]
Attualmente i banner in home sono troppo grandi, sono più alti degli articoli stessi. Sarebbe meglio rimpicciolirli o metterli di lato come quando si aprono gli articoli, altrimenti sono troppo invadenti già ora che ce ne sono 2.

**Comment by sinisimattia** [comment]
Quali banner intendi?

**Comment by Nootso** [comment]
Quelli degli sponsor

Andrea Nuzzo
Fondatore Sii come Bill e Consulente Billover 3.0
+39 3497906337
Facebook <http://www.facebook.com/andrea.nuzzo1996> | Instagram <http://www.instagram.com/nootso_> | LinkedIn <http://www.linkedin.com/in/andrea-nuzzo>
