### ISSUE TITLE
Aggiungere link al nome dell'autore

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#80]
Fare in modo che cliccando sul nome dell'autore si finisca nella sua bio della pagina "Redazione". Più collegamenti ci sono all'interno del sito più persone ci rimangono, e la SEO ne giova.

**Comment by sinisimattia** [comment]
Ok ottima idea. Ne ho un'altra. Se facessi una pagina autore con tutti i suoi articoli?
