### ISSUE TITLE
Quando apro la pagina di un determinato autore, in alto a destra risulta come se fossi entrato nel suo profilo

### ISSUE THREAD

**Issue by Nootso** [siicomebill/magazine#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nootso** [comment]
Credo sia solo un bug grafico perché quando clicco su un qualunque pulsante della dashboard agisce come se fossi nel profilo con cui giustamente sono loggato.
Esempio: 
1) Sono loggato con l'account mio. 
2) Clicco sulla pagina autore di Beatrice Gennaro
3) In alto a destra appare la foto di Beatrice Gennaro come se fossi loggato con il suo account
4) Poi però se ad esempio clicco su "Vai alla tua bacheca" o "Gestisci Profilo" appare "Ciao, Andrea Nuzzo"

Non so se mi sono spiegato ma credo di sì hahaha

**Comment by sinisimattia** [comment]
Risolto in aggiornamento passato
